-------------------------------------------------------------------------------
-- Target: main/DDL/EDLE_DW_DB/PNC_DATA_TRUST/VW_PNC_TRUST_SCORE_DASHBOARD.sql
--
-- Consumer-facing latest snapshot — Streamlit Portfolio + Dataset Detail bind
-- here instead of scanning PNC_DQ_RESULTS history directly.
-------------------------------------------------------------------------------

USE ROLE PNC_DEVELOPER_RL;
USE DATABASE EDLE_DW_DB;
USE SCHEMA PNC_DATA_TRUST;
USE WAREHOUSE PNC_AIML_WH;

CREATE OR REPLACE VIEW EDLE_DW_DB.PNC_DATA_TRUST.VW_PNC_TRUST_SCORE_DASHBOARD AS
WITH latest AS (
    SELECT
        r.*,
        ROW_NUMBER() OVER (PARTITION BY DATASET_ID ORDER BY SCORE_RUN_DATE DESC) AS rn
    FROM EDLE_DW_DB.PNC_DATA_TRUST.PNC_DQ_RESULTS r
)
SELECT
    l.DATASET_ID,
    l.DATASET_NAME,
    l.DATASET_FQN,
    l.DOMAIN,
    l.LAYER,
    l.SCORE_RUN_DATE                      AS AS_OF_DATE,
    l.TRUST_SCORE_OVERALL,
    l.TRUST_SCORE_TIER,
    l.DIM_OWNERSHIP_SCORE,
    l.DIM_SOURCE_SCORE,
    l.DIM_ISSUES_SCORE,
    l.DIM_TIMELINESS_SCORE,
    l.DIM_COMPLETENESS_KEY_PROPS_SCORE,
    l.DIM_PROFILING_SCORE,
    l.DIM_DEFINITIONS_SCORE,
    l.DIM_KEY_PROPERTIES_SCORE,
    l.DIM_USAGE_SCORE,
    l.DIM_FEEDBACK_SCORE,
    o.BUSINESS_OWNER_NAME,
    o.DATA_STEWARD_NAME,
    o.ASSIGNMENT_STATUS                   AS OWNERSHIP_ASSIGNMENT_STATUS,
    s.SOURCE_SYSTEM,
    s.CLASSIFICATION_TIER                 AS SOURCE_TIER,
    s.SLA_HOURS
FROM latest l
LEFT JOIN EDLE_DW_DB.PNC_DATA_TRUST.PNC_DATA_OWNERSHIP_REGISTRY o
       ON o.DATASET_ID = l.DATASET_ID
LEFT JOIN EDLE_DW_DB.PNC_DATA_TRUST.PNC_SOURCE_CLASSIFICATION s
       ON s.DATASET_ID = l.DATASET_ID
WHERE l.rn = 1;

GRANT SELECT ON VIEW EDLE_DW_DB.PNC_DATA_TRUST.VW_PNC_TRUST_SCORE_DASHBOARD
    TO ROLE PNC_AIML_DEVELOPER_RL;
