-------------------------------------------------------------------------------
-- Target: main/DDL/EDLE_DW_DB/PNC_DATA_TRUST/VW_PNC_DMF_LATEST_MEASUREMENTS.sql
--
-- Single bind point for Streamlit Cortex DQ page — shields UI from
-- SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS shape changes.
-------------------------------------------------------------------------------

USE ROLE PNC_DEVELOPER_RL;
USE DATABASE EDLE_DW_DB;
USE SCHEMA PNC_DATA_TRUST;
USE WAREHOUSE PNC_AIML_WH;

CREATE OR REPLACE VIEW EDLE_DW_DB.PNC_DATA_TRUST.VW_PNC_DMF_LATEST_MEASUREMENTS AS
WITH raw AS (
    SELECT
        METRIC_NAME,
        METRIC_VALUE,
        METRIC_STATUS,
        TABLE_NAME,
        SCHEMA_NAME,
        DATABASE_NAME,
        MEASUREMENT_TIME,
        ROW_NUMBER() OVER (
            PARTITION BY DATABASE_NAME, SCHEMA_NAME, TABLE_NAME, METRIC_NAME
            ORDER BY MEASUREMENT_TIME DESC
        ) AS rn
    FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS
    WHERE DATABASE_NAME = 'EDLE_DW_DB'
      AND SCHEMA_NAME IN ('PNC_DATA', 'PNC_DATA_TRUST')
)
SELECT
    DATABASE_NAME || '.' || SCHEMA_NAME || '.' || TABLE_NAME AS TABLE_FQN,
    METRIC_NAME,
    METRIC_VALUE,
    METRIC_STATUS,
    MEASUREMENT_TIME
FROM raw
WHERE rn = 1;

-- [USER]: align column names to actual DATA_QUALITY_MONITORING_RESULTS layout in EDLE-DEV.
-- [TODO] Join to PNC_DATASET_CATALOG on DATASET_FQN for DATASET_ID.

GRANT SELECT ON VIEW EDLE_DW_DB.PNC_DATA_TRUST.VW_PNC_DMF_LATEST_MEASUREMENTS
    TO ROLE PNC_AIML_DEVELOPER_RL;
