"""
Emit Snowflake INSERT seed scripts from the synthetic CSVs in ../data/.

Output: ../ddl/seed/91*_seed_*.sql

Each file is a sequence of multi-row INSERT statements (chunks of 200 rows,
well under Snowflake's 16 MB per-statement limit). You can paste any of
these straight into a Snowflake worksheet AFTER the DDL files (00..10)
have been run.

If you'd rather load via stage + COPY INTO (faster for production),
see ../ddl/91_seed_via_stage.sql for the alternative path.
"""

from __future__ import annotations

import math
import os
from datetime import date, datetime
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
SEED_DIR = ROOT / "ddl" / "seed"
SEED_DIR.mkdir(parents=True, exist_ok=True)

CHUNK_SIZE = 200
SCHEMA = "ASATTAR_TRUST_SCORE_POC.DQ_POC"


# --------------------------------------------------------------------------
# SQL value formatting
# --------------------------------------------------------------------------

def sql_literal(value) -> str:
    """Render a single Python value as a Snowflake literal."""
    if value is None:
        return "NULL"
    if value is pd.NaT:
        return "NULL"
    try:
        if pd.isna(value):
            return "NULL"
    except (TypeError, ValueError):
        pass
    if isinstance(value, float) and math.isnan(value):
        return "NULL"
    if isinstance(value, (np.floating,)) and np.isnan(value):
        return "NULL"
    if isinstance(value, bool) or isinstance(value, np.bool_):
        return "TRUE" if bool(value) else "FALSE"
    if isinstance(value, (int, np.integer)):
        return str(int(value))
    if isinstance(value, (float, np.floating)):
        return f"{float(value):.6f}".rstrip("0").rstrip(".") or "0"
    if isinstance(value, (datetime, pd.Timestamp)):
        # naive; matches TIMESTAMP_NTZ
        ts = pd.Timestamp(value).to_pydatetime()
        return "'" + ts.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3] + "'::TIMESTAMP_NTZ"
    if isinstance(value, date):
        return "'" + value.strftime("%Y-%m-%d") + "'::DATE"
    s = str(value).replace("'", "''")
    return f"'{s}'"


def render_chunk(table_fqn: str, columns: list[str], rows: list[tuple]) -> str:
    cols_csv = ", ".join(columns)
    values_lines = []
    for row in rows:
        rendered = ", ".join(sql_literal(v) for v in row)
        values_lines.append(f"  ({rendered})")
    return (
        f"INSERT INTO {table_fqn} ({cols_csv}) VALUES\n"
        + ",\n".join(values_lines)
        + ";\n"
    )


def write_seed_file(
    out_path: Path,
    table_name: str,
    df: pd.DataFrame,
    column_overrides: dict[str, str] | None = None,
    parse_dates: list[str] | None = None,
    parse_timestamps: list[str] | None = None,
) -> None:
    """
    Write `df` to `out_path` as chunked INSERT VALUES statements targeting
    `<SCHEMA>.<table_name>`.
    """
    df = df.copy()

    for col in parse_dates or []:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce").dt.date
    for col in parse_timestamps or []:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")

    columns = list(df.columns)
    rows = list(df.itertuples(index=False, name=None))

    table_fqn = f"{SCHEMA}.{table_name}"
    header = (
        f"-- Auto-generated by synthetic/generate_snowflake_seed.py\n"
        f"-- Target: {table_fqn}\n"
        f"-- Rows:   {len(rows):,}\n"
        f"-- Run AFTER the DDL files (00..10).\n"
        f"-- Idempotent: starts with TRUNCATE, so safe to re-paste + Run All.\n\n"
        f"USE SCHEMA {SCHEMA};\n\n"
        f"TRUNCATE TABLE {table_fqn};\n\n"
    )
    body_chunks = []
    for i in range(0, len(rows), CHUNK_SIZE):
        chunk = rows[i : i + CHUNK_SIZE]
        body_chunks.append(render_chunk(table_fqn, columns, chunk))

    out_path.write_text(header + "\n".join(body_chunks))
    print(f"  wrote {out_path.relative_to(ROOT)}  ({len(rows):,} rows)")


# --------------------------------------------------------------------------
# Per-table emitters
# --------------------------------------------------------------------------

def emit_weights() -> None:
    df = pd.read_csv(DATA_DIR / "PNC_TRUST_SCORE_WEIGHTS.csv")
    write_seed_file(
        SEED_DIR / "91a_seed_pnc_trust_score_weights.sql",
        "PNC_TRUST_SCORE_WEIGHTS",
        df,
        parse_dates=["EFFECTIVE_FROM"],
    )


def emit_source_classification() -> None:
    df = pd.read_csv(DATA_DIR / "PNC_SOURCE_CLASSIFICATION.csv")
    write_seed_file(
        SEED_DIR / "91b_seed_pnc_source_classification.sql",
        "PNC_SOURCE_CLASSIFICATION",
        df,
        parse_timestamps=["CREATED_AT", "UPDATED_AT"],
    )


def emit_ownership() -> None:
    df = pd.read_csv(DATA_DIR / "PNC_DATA_OWNERSHIP_REGISTRY.csv")
    write_seed_file(
        SEED_DIR / "91c_seed_pnc_data_ownership_registry.sql",
        "PNC_DATA_OWNERSHIP_REGISTRY",
        df,
        parse_dates=["LAST_CONFIRMED_DATE", "NEXT_REVIEW_DUE_DATE"],
        parse_timestamps=["CREATED_AT", "UPDATED_AT"],
    )


def emit_keys() -> None:
    df = pd.read_csv(DATA_DIR / "PNC_KEY_PROPERTY_REGISTRY.csv")
    write_seed_file(
        SEED_DIR / "91d_seed_pnc_key_property_registry.sql",
        "PNC_KEY_PROPERTY_REGISTRY",
        df,
        parse_timestamps=["LAST_PROFILED_AT", "LOAD_DATE"],
    )


def emit_dq_results() -> None:
    df = pd.read_csv(DATA_DIR / "PNC_DQ_RESULTS.csv")
    write_seed_file(
        SEED_DIR / "91e_seed_pnc_dq_results.sql",
        "PNC_DQ_RESULTS",
        df,
        parse_dates=["SCORE_RUN_DATE", "DIM_OWNERSHIP_LAST_CONFIRMED"],
        parse_timestamps=[
            "DIM_ISSUES_LAST_FAILURE_AT",
            "DIM_TIMELINESS_MAX_LOAD_DATE",
            "LOAD_DATE",
        ],
    )


def emit_dim_long() -> None:
    df = pd.read_csv(DATA_DIR / "PNC_DQ_DIMENSION_RESULTS.csv")
    # The synthetic generator does not populate raw metric / notes columns
    # for the long fact, so add empty columns to match the table shape.
    for col in ("RAW_METRIC_NAME", "RAW_METRIC_VALUE", "NOTES", "LOAD_DATE"):
        if col not in df.columns:
            df[col] = None
    df = df[
        [
            "DATASET_ID",
            "DATASET_NAME",
            "DOMAIN",
            "SCORE_RUN_DATE",
            "DIMENSION_CODE",
            "DIMENSION_NAME",
            "RAW_METRIC_NAME",
            "RAW_METRIC_VALUE",
            "SCORE",
            "STATUS",
            "NOTES",
            "LOAD_DATE",
        ]
    ]
    write_seed_file(
        SEED_DIR / "91f_seed_pnc_dq_dimension_results.sql",
        "PNC_DQ_DIMENSION_RESULTS",
        df,
        parse_dates=["SCORE_RUN_DATE"],
        parse_timestamps=["LOAD_DATE"],
    )


# --------------------------------------------------------------------------
# Master runner
# --------------------------------------------------------------------------

def main() -> None:
    print(f"[trust-score] writing seed SQL to {SEED_DIR.relative_to(ROOT)}/ ...")
    emit_weights()
    emit_source_classification()
    emit_ownership()
    emit_keys()
    emit_dq_results()
    emit_dim_long()

    # Master driver that just \i's the others in order. Snowflake worksheets
    # don't support \i, so we instead write a one-pager that documents order.
    driver = SEED_DIR.parent / "91_seed_data.sql"
    driver.write_text(
        "-------------------------------------------------------------------------------\n"
        "-- 91_seed_data.sql  (driver / index)\n"
        "--\n"
        "-- Run the files in ddl/seed/ in this order, in a Snowflake worksheet:\n"
        "--   1. 91a_seed_pnc_trust_score_weights.sql\n"
        "--   2. 91b_seed_pnc_source_classification.sql\n"
        "--   3. 91c_seed_pnc_data_ownership_registry.sql\n"
        "--   4. 91d_seed_pnc_key_property_registry.sql\n"
        "--   5. 91e_seed_pnc_dq_results.sql\n"
        "--   6. 91f_seed_pnc_dq_dimension_results.sql\n"
        "--\n"
        "-- (Snowflake worksheets do not have a multi-file include directive,\n"
        "-- so this file is intentionally just a checklist.)\n"
        "-------------------------------------------------------------------------------\n"
    )
    print(f"  wrote {driver.relative_to(ROOT)}")
    print("[trust-score] done.")


if __name__ == "__main__":
    main()
