-- Auto-generated by synthetic/generate_snowflake_seed.py
-- Target: ASATTAR_TRUST_SCORE_POC.DQ_POC.PNC_TRUST_SCORE_WEIGHTS
-- Rows:   10
-- Run AFTER the DDL files (00..10).
-- Idempotent: starts with TRUNCATE, so safe to re-paste + Run All.

USE SCHEMA ASATTAR_TRUST_SCORE_POC.DQ_POC;

TRUNCATE TABLE ASATTAR_TRUST_SCORE_POC.DQ_POC.PNC_TRUST_SCORE_WEIGHTS;

INSERT INTO ASATTAR_TRUST_SCORE_POC.DQ_POC.PNC_TRUST_SCORE_WEIGHTS (DIMENSION_CODE, DIMENSION_NAME, WEIGHT_PCT, EFFECTIVE_FROM) VALUES
  ('OWNERSHIP', 'Data Ownership', 12, '2026-05-06'::DATE),
  ('SOURCE', 'Data Source', 10, '2026-05-06'::DATE),
  ('ISSUES', 'Active Issues', 12, '2026-05-06'::DATE),
  ('TIMELINESS', 'Timeliness', 14, '2026-05-06'::DATE),
  ('COMPLETENESS_KEY_PROPS', 'Completeness of Key Properties', 14, '2026-05-06'::DATE),
  ('PROFILING', 'Data Profiling', 12, '2026-05-06'::DATE),
  ('DEFINITIONS', 'Data Definitions', 8, '2026-05-06'::DATE),
  ('KEY_PROPERTIES', 'Key Properties', 8, '2026-05-06'::DATE),
  ('USAGE', 'Usage', 6, '2026-05-06'::DATE),
  ('FEEDBACK', 'User Feedback', 4, '2026-05-06'::DATE);
