-- Auto-generated by synthetic/generate_snowflake_seed.py
-- Target: ASATTAR_TRUST_SCORE_POC.DQ_POC.PNC_DATA_OWNERSHIP_REGISTRY
-- Rows:   7
-- Run AFTER the DDL files (00..10).
-- Idempotent: starts with TRUNCATE, so safe to re-paste + Run All.

USE SCHEMA ASATTAR_TRUST_SCORE_POC.DQ_POC;

TRUNCATE TABLE ASATTAR_TRUST_SCORE_POC.DQ_POC.PNC_DATA_OWNERSHIP_REGISTRY;

INSERT INTO ASATTAR_TRUST_SCORE_POC.DQ_POC.PNC_DATA_OWNERSHIP_REGISTRY (DATASET_ID, DATASET_NAME, DATASET_FQN, DOMAIN, BUSINESS_OWNER_NAME, BUSINESS_OWNER_EMAIL, DATA_STEWARD_NAME, DATA_STEWARD_EMAIL, TECHNICAL_OWNER_NAME, TECHNICAL_OWNER_EMAIL, ASSIGNMENT_STATUS, LAST_CONFIRMED_DATE, NEXT_REVIEW_DUE_DATE, NOTES, UPDATED_AT, UPDATED_BY) VALUES
  ('DS_POSITION_REPORT', 'Workday Position Report', 'EDLE_DW_DB.PNC_DATA.DT_POSITION_REPORT', 'P&C', 'Paul Field', 'paul.field@wbd.com', 'TBD - critical pre-Design gate', NULL, 'Data Engineering', 'data-eng@wbd.com', 'PROVISIONAL', '2026-03-30'::DATE, '2026-09-26'::DATE, '~815K rows, ~200 attributes', '2026-05-06 15:37:37.270'::TIMESTAMP_NTZ, 'prototype'),
  ('DS_POSITION_REPORT_VW', 'Position Report Public View', 'EDLE_PUBL_DB.PNC_DATA.STG_POSITION_REPORT_VW', 'P&C', 'Paul Field', 'paul.field@wbd.com', NULL, NULL, 'Data Engineering', 'data-eng@wbd.com', 'PROVISIONAL', '2025-11-13'::DATE, '2026-05-12'::DATE, NULL, '2026-05-06 15:37:37.270'::TIMESTAMP_NTZ, 'prototype'),
  ('DS_TRENDED_REPORT', 'Workday Trended Report', 'EDLE_DW_DB.PNC_DATA.DT_TRENDED_REPORT', 'P&C', 'Perri Ma', 'perri.ma@wbd.com', NULL, NULL, 'Data Engineering', 'data-eng@wbd.com', 'PROVISIONAL', '2025-12-07'::DATE, '2026-06-05'::DATE, 'Compensation explicitly excluded; IS_DELETED_FROM_FILE flag not surfaced as DQ signal', '2026-05-06 15:37:37.270'::TIMESTAMP_NTZ, 'prototype'),
  ('DS_TRENDED_REPORT_VW', 'Trended Report Public View', 'EDLE_PUBL_DB.PNC_DATA.STG_TRENDED_REPORT_VW', 'P&C', 'Perri Ma', 'perri.ma@wbd.com', NULL, NULL, 'Data Engineering', 'data-eng@wbd.com', 'PROVISIONAL', '2026-01-19'::DATE, '2026-07-18'::DATE, NULL, '2026-05-06 15:37:37.271'::TIMESTAMP_NTZ, 'prototype'),
  ('DS_WORKPLACE_TRANSITION', 'Workplace Transition / RTO', 'EDLE_DW_DB.PNC_DATA.TRAN_DT_WRKPLCTRNS_CONSOLIDATED', 'P&C', NULL, NULL, NULL, NULL, 'Data Engineering', 'data-eng@wbd.com', 'UNASSIGNED', NULL, NULL, 'Badge coverage partial: CCURE, DSX, RS2, Atlanta, Hudson Yards only', '2026-05-06 15:37:37.271'::TIMESTAMP_NTZ, 'prototype'),
  ('DS_BEELINE_CONSO', 'Beeline Consolidated (FPA)', 'EDLE_DW_DB.FPA_DATA.DT_BEELINE_CONSO', 'FPA', NULL, NULL, NULL, NULL, 'Data Engineering', 'data-eng@wbd.com', 'UNASSIGNED', NULL, NULL, 'PENDING FPA data-owner approval', '2026-05-06 15:37:37.271'::TIMESTAMP_NTZ, 'prototype'),
  ('DS_BEELINE_WORKER', 'Beeline WBD Worker (FPA)', 'EDLE_PUBL_DB.FPA_DATA.STG_BEELINE_WBD_WORKER', 'FPA', NULL, NULL, NULL, NULL, 'Data Engineering', 'data-eng@wbd.com', 'UNASSIGNED', NULL, NULL, 'PENDING FPA data-owner approval; ManagerID not in current view', '2026-05-06 15:37:37.271'::TIMESTAMP_NTZ, 'prototype');
