-------------------------------------------------------------------------------
-- edl/ddl/00_privilege_self_check.sql
--
-- Read-only privilege introspection for EDLE-DEV before committing to a
-- governance layout, native-DMF wiring, or Streamlit deploy. Avoids
-- SNOWFLAKE.ACCOUNT_USAGE (not readable to PNC roles) and avoids bare
-- DECLARE/BEGIN at worksheet top level — each check is plain SQL + SHOW +
-- RESULT_SCAN(LAST_QUERY_ID()).
--
-- HOW TO RUN (Snowsight worksheet or Notebook)
-- --------------------------------------------
-- Option A — one session, two role passes:
--   1. Run Section A (all cells) as PNC_DEVELOPER_RL.
--   2. USE ROLE PNC_AIML_DEVELOPER_RL; run Section B (all cells).
--   3. Run Section C (gap analysis) — both temp tables must exist.
-- Option B — split into Notebook cells at each `-- ## Cell N` banner.
--
-- Copy Section C output back to the build conversation.
-------------------------------------------------------------------------------

-- ===========================================================================
-- SECTION A — PNC_DEVELOPER_RL (creator / governance / Streamlit)
-- ===========================================================================

USE ROLE PNC_DEVELOPER_RL;
-- [USER]: confirm warehouse name if PNC_AIML_WH is not granted to this role
USE WAREHOUSE PNC_AIML_WH;

SET ROLE_LABEL = 'PNC_DEVELOPER_RL';

CREATE OR REPLACE TEMPORARY TABLE PRIVILEGE_CHECK_PNC_DEVELOPER (
    ROLE_NAME   STRING,
    SECTION     STRING,
    CHECK_NAME  STRING,
    RESULT      STRING,
    DETAIL      STRING
);


-- ## Cell A1 — Session context
INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A1. Session',
    'CURRENT_ROLE / USER / WAREHOUSE / REGION / ACCOUNT',
    'INFO',
    'role=' || CURRENT_ROLE()
        || '; user=' || CURRENT_USER()
        || '; warehouse=' || COALESCE(CURRENT_WAREHOUSE(), '<none>')
        || '; region=' || CURRENT_REGION()
        || '; account=' || CURRENT_ACCOUNT();


-- ## Cell A2 — Roles granted to this role (summary)
SHOW GRANTS TO ROLE PNC_DEVELOPER_RL;

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A2. Grants',
    'Child roles / database roles granted TO PNC_DEVELOPER_RL',
    'INFO',
    'count=' || COUNT(*)::STRING
        || '; sample=' || COALESCE(MAX("name"), '<none>')
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "granted_on" IN ('ROLE', 'DATABASE_ROLE');


-- ## Cell A3 — Database visibility (account)
INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A3. Visibility',
    'Databases visible (INFORMATION_SCHEMA.DATABASES)',
    CASE WHEN COUNT(*) >= 4 THEN 'PASS' ELSE 'WARN' END,
    'visible_db_count=' || COUNT(*)::STRING
FROM INFORMATION_SCHEMA.DATABASES
WHERE DATABASE_NAME IN ('EDLE_DW_DB', 'EDLE_INT_DB', 'EDLE_PUBL_DB', 'TECH_DW_DB');


-- ## Cell A4 — Schemas visible per candidate DB
INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT $ROLE_LABEL, 'A4. Schemas', 'EDLE_DW_DB schema count', CASE WHEN c > 0 THEN 'PASS' ELSE 'FAIL' END, 'schema_count=' || c
FROM (SELECT COUNT(*) AS c FROM EDLE_DW_DB.INFORMATION_SCHEMA.SCHEMATA);

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT $ROLE_LABEL, 'A4. Schemas', 'EDLE_INT_DB schema count', CASE WHEN c > 0 THEN 'PASS' ELSE 'FAIL' END, 'schema_count=' || c
FROM (SELECT COUNT(*) AS c FROM EDLE_INT_DB.INFORMATION_SCHEMA.SCHEMATA);

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT $ROLE_LABEL, 'A4. Schemas', 'EDLE_PUBL_DB schema count', CASE WHEN c > 0 THEN 'PASS' ELSE 'FAIL' END, 'schema_count=' || c
FROM (SELECT COUNT(*) AS c FROM EDLE_PUBL_DB.INFORMATION_SCHEMA.SCHEMATA);

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT $ROLE_LABEL, 'A4. Schemas', 'TECH_DW_DB schema count', CASE WHEN c > 0 THEN 'PASS' ELSE 'FAIL' END, 'schema_count=' || c
FROM (SELECT COUNT(*) AS c FROM TECH_DW_DB.INFORMATION_SCHEMA.SCHEMATA);


-- ## Cell A5 — Base tables visible in PNC_DATA + TECH_AIML
INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT $ROLE_LABEL, 'A5. Tables', 'EDLE_DW_DB.PNC_DATA base tables', CASE WHEN c > 0 THEN 'PASS' ELSE 'FAIL' END, 'table_count=' || c
FROM (
    SELECT COUNT(*) AS c
    FROM EDLE_DW_DB.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'PNC_DATA' AND TABLE_TYPE = 'BASE TABLE'
);

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT $ROLE_LABEL, 'A5. Tables', 'TECH_DW_DB.TECH_AIML objects', CASE WHEN c > 0 THEN 'PASS' ELSE 'WARN' END, 'object_count=' || c
FROM (
    SELECT COUNT(*) AS c
    FROM TECH_DW_DB.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'TECH_AIML'
);


-- ## Cell A6 — CREATE privileges (SHOW GRANTS TO ROLE)
SHOW GRANTS TO ROLE PNC_DEVELOPER_RL;

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A6. CREATE',
    'CREATE DATABASE on account',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
    'matching_grants=' || COUNT(*)::STRING
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'CREATE DATABASE';

SHOW GRANTS TO ROLE PNC_DEVELOPER_RL;

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A6. CREATE',
    'CREATE SCHEMA on EDLE_DW_DB',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
    'matching_grants=' || COUNT(*)::STRING
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'CREATE SCHEMA'
  AND "name" = 'EDLE_DW_DB';

SHOW GRANTS TO ROLE PNC_DEVELOPER_RL;

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A6. CREATE',
    'CREATE SCHEMA on EDLE_INT_DB',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'WARN' END,
    'matching_grants=' || COUNT(*)::STRING
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'CREATE SCHEMA'
  AND "name" = 'EDLE_INT_DB';

SHOW GRANTS ON SCHEMA EDLE_DW_DB.PNC_DATA;

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A6. CREATE',
    'CREATE STAGE / STREAMLIT on EDLE_DW_DB.PNC_DATA',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
    'matching_grants=' || COUNT(*)::STRING
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" IN ('CREATE STAGE', 'CREATE STREAMLIT')
  AND "grantee_name" = 'PNC_DEVELOPER_RL';


-- ## Cell A7 — DMF readiness
INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A7. DMF',
    'SNOWFLAKE.DATA_METRIC_USER via APPLICABLE_ROLES',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
    'applicable_roles=' || COUNT(*)::STRING
FROM INFORMATION_SCHEMA.APPLICABLE_ROLES
WHERE ROLE_NAME = 'DATA_METRIC_USER'
  AND ROLE_OWNER = 'SNOWFLAKE';

SHOW GRANTS TO ROLE PNC_DEVELOPER_RL;

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A7. DMF',
    'EXECUTE DATA METRIC FUNCTION (account)',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
    'matching_grants=' || COUNT(*)::STRING
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'EXECUTE DATA METRIC FUNCTION';

-- [USER]: set to a DT_* table PNC_DEVELOPER_RL owns (required for ALTER TABLE ADD DMF)
SET SAMPLE_OWNED_TABLE = 'EDLE_DW_DB.PNC_DATA.DT_TRENDED_REPORT';

SHOW GRANTS ON TABLE IDENTIFIER($SAMPLE_OWNED_TABLE);

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A7. DMF',
    'OWNERSHIP on sample scored table',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
    'table=' || $SAMPLE_OWNED_TABLE || '; ownership_grants=' || COUNT(*)::STRING
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'OWNERSHIP'
  AND "grantee_name" = 'PNC_DEVELOPER_RL';

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A7. DMF',
    'Manual: read DATA_QUALITY_MONITORING_RESULTS',
    'MANUAL',
    'Run: SELECT * FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS LIMIT 1; '
        || 'Expect rows or empty set — not Insufficient privileges.';


-- ## Cell A8 — Cortex usage
INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A8. Cortex',
    'SNOWFLAKE.CORTEX_USER via APPLICABLE_ROLES',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
    'applicable_roles=' || COUNT(*)::STRING
FROM INFORMATION_SCHEMA.APPLICABLE_ROLES
WHERE ROLE_NAME = 'CORTEX_USER'
  AND ROLE_OWNER = 'SNOWFLAKE';

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A8. Cortex',
    'Manual: Cortex COMPLETE smoke test',
    'MANUAL',
    'Run: SELECT SNOWFLAKE.CORTEX.COMPLETE(''snowflake-cortex'',''Reply OK only'') AS r;';


-- ## Cell A9 — Warehouses visible
SHOW WAREHOUSES;

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A9. Warehouse',
    'Warehouses visible to role',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
    'warehouse_count=' || COUNT(*)::STRING
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A9. Warehouse',
    'Session warehouse USAGE',
    CASE WHEN CURRENT_WAREHOUSE() IS NOT NULL THEN 'PASS' ELSE 'FAIL' END,
    'current_warehouse=' || COALESCE(CURRENT_WAREHOUSE(), '<none>');


-- ## Cell A10 — Manual SELECT on source (uncomment if you want an automatic probe)
INSERT INTO PRIVILEGE_CHECK_PNC_DEVELOPER (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'A10. Source read',
    'Manual: SELECT COUNT on DT_TRENDED_REPORT',
    'MANUAL',
    'Run: SELECT COUNT(*) FROM EDLE_DW_DB.PNC_DATA.DT_TRENDED_REPORT;';


-- ## Cell A11 — Section A summary (copy this result set)
SELECT ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL
FROM PRIVILEGE_CHECK_PNC_DEVELOPER
ORDER BY SECTION, CHECK_NAME;


-- ===========================================================================
-- SECTION B — PNC_AIML_DEVELOPER_RL (DMF execution / AIML reads)
-- ===========================================================================

USE ROLE PNC_AIML_DEVELOPER_RL;
USE WAREHOUSE PNC_AIML_WH_UOM;

SET ROLE_LABEL = 'PNC_AIML_DEVELOPER_RL';

CREATE OR REPLACE TEMPORARY TABLE PRIVILEGE_CHECK_PNC_AIML (
    ROLE_NAME   STRING,
    SECTION     STRING,
    CHECK_NAME  STRING,
    RESULT      STRING,
    DETAIL      STRING
);


-- ## Cell B1 — Session context
INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B1. Session',
    'CURRENT_ROLE / USER / WAREHOUSE / REGION / ACCOUNT',
    'INFO',
    'role=' || CURRENT_ROLE()
        || '; user=' || CURRENT_USER()
        || '; warehouse=' || COALESCE(CURRENT_WAREHOUSE(), '<none>')
        || '; region=' || CURRENT_REGION()
        || '; account=' || CURRENT_ACCOUNT();


-- ## Cell B2 — Roles granted
SHOW GRANTS TO ROLE PNC_AIML_DEVELOPER_RL;

INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B2. Grants',
    'Child roles / database roles granted TO PNC_AIML_DEVELOPER_RL',
    'INFO',
    'count=' || COUNT(*)::STRING
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "granted_on" IN ('ROLE', 'DATABASE_ROLE');


-- ## Cell B3 — Database visibility
INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B3. Visibility',
    'Databases visible (INFORMATION_SCHEMA.DATABASES)',
    CASE WHEN COUNT(*) >= 4 THEN 'PASS' ELSE 'WARN' END,
    'visible_db_count=' || COUNT(*)::STRING
FROM INFORMATION_SCHEMA.DATABASES
WHERE DATABASE_NAME IN ('EDLE_DW_DB', 'EDLE_INT_DB', 'EDLE_PUBL_DB', 'TECH_DW_DB');


-- ## Cell B4 — Schemas visible
INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT $ROLE_LABEL, 'B4. Schemas', 'EDLE_DW_DB.PNC_DATA visible', CASE WHEN c > 0 THEN 'PASS' ELSE 'FAIL' END, 'schema_count=' || c
FROM (SELECT COUNT(*) AS c FROM EDLE_DW_DB.INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'PNC_DATA');

INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT $ROLE_LABEL, 'B4. Schemas', 'TECH_DW_DB.TECH_AIML visible', CASE WHEN c > 0 THEN 'PASS' ELSE 'FAIL' END, 'schema_count=' || c
FROM (SELECT COUNT(*) AS c FROM TECH_DW_DB.INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'TECH_AIML');


-- ## Cell B5 — Tables visible (read path)
INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT $ROLE_LABEL, 'B5. Tables', 'EDLE_DW_DB.PNC_DATA base tables (_R read)', CASE WHEN c > 0 THEN 'PASS' ELSE 'FAIL' END, 'table_count=' || c
FROM (
    SELECT COUNT(*) AS c
    FROM EDLE_DW_DB.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'PNC_DATA' AND TABLE_TYPE = 'BASE TABLE'
);

INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B5. AIML',
    'Manual: WORKFORCE_ANALYTICS_AGENT accessible',
    'MANUAL',
    'Open Snowsight Cortex Agents → TECH_DW_DB.TECH_AIML.WORKFORCE_ANALYTICS_AGENT '
        || 'or run DESCRIBE/SHOW per your account''s Agent DDL.';

INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B5. AIML',
    'Manual: SV_POSITION_TRENDED queryable',
    'MANUAL',
    'Run: SELECT * FROM TECH_DW_DB.TECH_AIML.SV_POSITION_TRENDED LIMIT 1;';


-- ## Cell B6 — CREATE privileges (expect FAIL — read-only role)
SHOW GRANTS TO ROLE PNC_AIML_DEVELOPER_RL;

INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B6. CREATE',
    'CREATE SCHEMA on EDLE_DW_DB (should be absent)',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'WARN' END,
    'matching_grants=' || COUNT(*)::STRING
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'CREATE SCHEMA'
  AND "name" = 'EDLE_DW_DB';


-- ## Cell B7 — DMF readiness (execution role)
INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B7. DMF',
    'SNOWFLAKE.DATA_METRIC_USER via APPLICABLE_ROLES',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
    'applicable_roles=' || COUNT(*)::STRING
FROM INFORMATION_SCHEMA.APPLICABLE_ROLES
WHERE ROLE_NAME = 'DATA_METRIC_USER'
  AND ROLE_OWNER = 'SNOWFLAKE';

SHOW GRANTS TO ROLE PNC_AIML_DEVELOPER_RL;

INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B7. DMF',
    'EXECUTE DATA METRIC FUNCTION (account)',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
    'matching_grants=' || COUNT(*)::STRING
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'EXECUTE DATA METRIC FUNCTION';

SET SAMPLE_SCORED_TABLE = 'EDLE_DW_DB.PNC_DATA.DT_TRENDED_REPORT';

SHOW GRANTS ON TABLE IDENTIFIER($SAMPLE_SCORED_TABLE);

INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B7. DMF',
    'OWNERSHIP on sample scored table (expect FAIL for AIML role)',
    CASE WHEN COUNT(*) > 0 THEN 'WARN' ELSE 'PASS' END,
    'table=' || $SAMPLE_SCORED_TABLE
        || '; note=DMFs attach under DEVELOPER ownership; AIML executes measurements'
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "privilege" = 'OWNERSHIP'
  AND "grantee_name" = 'PNC_AIML_DEVELOPER_RL';

INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B7. DMF',
    'Manual: read DATA_QUALITY_MONITORING_RESULTS',
    'MANUAL',
    'Run: SELECT * FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS LIMIT 1;';


-- ## Cell B8 — Cortex + Agent
INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B8. Cortex',
    'SNOWFLAKE.CORTEX_USER via APPLICABLE_ROLES',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
    'applicable_roles=' || COUNT(*)::STRING
FROM INFORMATION_SCHEMA.APPLICABLE_ROLES
WHERE ROLE_NAME = 'CORTEX_USER'
  AND ROLE_OWNER = 'SNOWFLAKE';

INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B8. Cortex',
    'Manual: query WORKFORCE_ANALYTICS_AGENT',
    'MANUAL',
    'Run agent UI or: SELECT SYSTEM$AGENT_RUN_HISTORY(''TECH_DW_DB.TECH_AIML.WORKFORCE_ANALYTICS_AGENT'') LIMIT 1; '
        || '(exact API may vary — confirm in Snowsight Cortex Agents).';


-- ## Cell B9 — Warehouses
SHOW WAREHOUSES;

INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B9. Warehouse',
    'Warehouses visible to role',
    CASE WHEN COUNT(*) > 0 THEN 'PASS' ELSE 'FAIL' END,
    'warehouse_count=' || COUNT(*)::STRING
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B9. Warehouse',
    'Session warehouse USAGE',
    CASE WHEN CURRENT_WAREHOUSE() IS NOT NULL THEN 'PASS' ELSE 'FAIL' END,
    'current_warehouse=' || COALESCE(CURRENT_WAREHOUSE(), '<none>');


-- ## Cell B10 — Manual SELECT on governed source
INSERT INTO PRIVILEGE_CHECK_PNC_AIML (ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL)
SELECT
    $ROLE_LABEL,
    'B10. Source read',
    'Manual: SELECT COUNT on DT_TRENDED_REPORT',
    'MANUAL',
    'Run: SELECT COUNT(*) FROM EDLE_DW_DB.PNC_DATA.DT_TRENDED_REPORT;';


-- ## Cell B11 — Section B summary
SELECT ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL
FROM PRIVILEGE_CHECK_PNC_AIML
ORDER BY SECTION, CHECK_NAME;


-- ===========================================================================
-- SECTION C — Cross-role gap analysis (run after A and B in same session)
-- ===========================================================================

-- ## Cell C1 — Side-by-side PASS/FAIL comparison
SELECT
    COALESCE(d.CHECK_NAME, a.CHECK_NAME)              AS CHECK_NAME,
    d.RESULT                                          AS PNC_DEVELOPER_RL_RESULT,
    d.DETAIL                                          AS PNC_DEVELOPER_RL_DETAIL,
    a.RESULT                                          AS PNC_AIML_DEVELOPER_RL_RESULT,
    a.DETAIL                                          AS PNC_AIML_DEVELOPER_RL_DETAIL,
    CASE
        WHEN d.RESULT = a.RESULT THEN 'ALIGNED'
        WHEN d.RESULT IN ('PASS', 'INFO') AND a.RESULT IN ('FAIL', 'WARN') THEN 'AIML_GAP'
        WHEN a.RESULT IN ('PASS', 'INFO') AND d.RESULT IN ('FAIL', 'WARN') THEN 'DEVELOPER_GAP'
        ELSE 'MIXED'
    END                                               AS GAP_SIGNAL
FROM PRIVILEGE_CHECK_PNC_DEVELOPER d
FULL OUTER JOIN PRIVILEGE_CHECK_PNC_AIML a
    ON d.CHECK_NAME = a.CHECK_NAME
ORDER BY GAP_SIGNAL DESC, CHECK_NAME;

-- ## Cell C2 — Checks that likely need a DBA grant (any role FAIL on DMF/Cortex/CREATE)
SELECT ROLE_NAME, SECTION, CHECK_NAME, RESULT, DETAIL
FROM (
    SELECT * FROM PRIVILEGE_CHECK_PNC_DEVELOPER
    UNION ALL
    SELECT * FROM PRIVILEGE_CHECK_PNC_AIML
) u
WHERE RESULT IN ('FAIL', 'WARN')
  AND SECTION ILIKE ANY ('%DMF%', '%Cortex%', '%CREATE%')
ORDER BY ROLE_NAME, CHECK_NAME;
