-- Additive columns to keep the POC DT_TRENDED_REPORT in step with the
-- production EDL schema. Repointed from EDLE_DW_DB.PNC_DATA to the POC
-- schema; ADMIN_DB tag clauses stripped (same reason as DT_TRENDED_REPORT.sql).

ALTER TABLE ASATTAR_TRUST_SCORE_POC.DQ_POC.DT_TRENDED_REPORT 
ADD COLUMN IF NOT EXISTS Timezone VARCHAR(16777216);

ALTER TABLE ASATTAR_TRUST_SCORE_POC.DQ_POC.DT_TRENDED_REPORT 
ADD COLUMN IF NOT EXISTS Manager_Timezone VARCHAR(16777216);

ALTER TABLE ASATTAR_TRUST_SCORE_POC.DQ_POC.DT_TRENDED_REPORT 
ADD COLUMN IF NOT EXISTS Manager_Country VARCHAR(16777216);

ALTER TABLE ASATTAR_TRUST_SCORE_POC.DQ_POC.DT_TRENDED_REPORT 
ADD COLUMN IF NOT EXISTS Manager_City VARCHAR(16777216);

ALTER TABLE ASATTAR_TRUST_SCORE_POC.DQ_POC.DT_TRENDED_REPORT 
ADD COLUMN IF NOT EXISTS brgambassadors VARCHAR(16777216);

ALTER TABLE ASATTAR_TRUST_SCORE_POC.DQ_POC.DT_TRENDED_REPORT 
ADD COLUMN IF NOT EXISTS Direct_And_Indirect_Report_Count NUMBER(38,0);